# Generated by Django 6.0.3 on 2026-04-06 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('max_passageiros', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Aviões',
                'ordering': ['fabricante', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('aviao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voos', to='flights.aviao')),
            ],
            options={
                'verbose_name_plural': 'Voos',
                'ordering': ['data', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_assento', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='accounts.cliente')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='flights.voo')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('voo', 'numero_assento'), name='unique_assento_por_voo'), models.UniqueConstraint(fields=('voo', 'cliente'), name='unique_cliente_por_voo')],
            },
        ),
    ]
