# Generated by Django 6.0.3 on 2026-04-06 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('max_passageiros', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Avioes',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('aviao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voos', to='voos.aviao')),
            ],
            options={
                'verbose_name_plural': 'Voos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_assento', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='voos.cliente')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='voos.voo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voo', 'numero_assento'), name='unique_assento_por_voo'), models.UniqueConstraint(fields=('voo', 'cliente'), name='unique_cliente_por_voo')],
            },
        ),
    ]
