# Generated by Django 6.0.3 on 2026-04-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviao',
            options={'ordering': ['fabricante', 'modelo'], 'verbose_name_plural': 'Avioes'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='voo',
            options={'ordering': ['data', 'horario'], 'verbose_name_plural': 'Voos'},
        ),
    ]
